### ISSUE TITLE
Friend Point on Minimap over Ingame Window

### ISSUE THREAD

**Issue by NevendyND** [jaycewhite/MiniMappingway#11]
I think the Picture should explain it
but i can understand when its to much to fix, i mean when do you have a Ingame Window over the Minimap.

![hfth](https://user-images.githubusercontent.com/28860034/190925655-fc961be0-b9d0-4dbe-bdbc-77e4f446b54e.PNG)

**Comment by jaycewhite** [comment]
Thanks for the feedback! This is a limitation of drawing an overlay onto the game window unfortunately, there's no good way to fix this as far as I know. I am looking to possibly see if I can use the built in party markers to display people which should solve this, but at the moment its on the backburner and may come with its own limitations. I'm happy to either keep this issue open and I can update it if there's any progress, or we can close it, either is fine!
