### ISSUE TITLE
Add option to hide during cutscene

### ISSUE THREAD

**Issue by IUseExcessivelyLongUsernamesForNoReason** [jaycewhite/MiniMappingway#17]
Feature request; would if be possible to please add an option to hide the dots during cutscenes?

**Comment by IUseExcessivelyLongUsernamesForNoReason** [comment]
I do not think "fix" is the right word in this case. The addon works perfectly, this is a feature request, not a bug.
That aside, I am still seeing dots during cutscenes, and there is no new option in the settings for it. No big deal though, it is such a small thing, and it is important to respect volunteer developers time. I would not have even checked back if github did not email me.

**Comment by jaycewhite** [comment]
Hi! 
I kinda didn't look at this github for a while until 6.3, so apologies for not looking at this sooner! I'm currently pretty busy because i've just moved, but once I get my pc setup etc. and I have a minute i'll read through to comments properly and see what I can do! Thanks!

**Comment by jaycewhite** [comment]
Closing this RE: #23
