### ISSUE TITLE
Friend Pips not showing on minimap (Bug)

### ISSUE THREAD

**Issue by Phreezey** [jaycewhite/MiniMappingway#25]
After the 6.4 update, I've noticed that Minimappingway does not show my friend pips regardless of if I have the setting enabled or not. I have attached a screenshot to show the issue directly. I'm not sure what's causing this - but it still recognizes FC Mates over friends. I have tried restarting the mod, changing the values, re-adding friends, and even reinstalling the mod, but nothing has yet worked. 

![MmapwaybugShot](https://github.com/jaycewhite/MiniMappingway/assets/134709934/b94255ba-0dca-4cb1-a593-bfd34a264f71)

**Comment by jaycewhite** [comment]
Fixed in 34e7f2361a5b901441527c75b54db8af772a0aeb
