### ISSUE TITLE
Orange Dots for friends arent showing on the map

### ISSUE THREAD

**Issue by Jibby2121** [jaycewhite/MiniMappingway#26]
Not sure how to ad dthis to the other persons issue on this but I am having it as well since the 6.4 update. 

Can only see FC markers but not friends even with the priorities set.

**Comment by NyxenWTF** [comment]
Same, and I was wondering if I was going crazy or not

**Comment by jaycewhite** [comment]
Fixed in 34e7f2361a5b901441527c75b54db8af772a0aeb I believe
